apiVersion: v1
kind: ConfigMap
metadata:
  namespace: success-221
  name: api-successs-2211-properties
  labels:
    part-of: k8s-success
    component: backend-server
    name: api-success
    instance: api-success-2211
    version: 1.0.0
    managed-by: kubectl
data:
  spring_profiles_active: "dev"
  application_role: "ALL"
  postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"
