apiVersion: v1
kind: Secret
metadata:
  namespace: success-221
  name: api-success-2211-postgresql
  labels:
    part-of: k8s-success
    component: backend-server
    name: api-success
    instance: api-success-2211
    version: 1.0.0
    managed-by: kubectl
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "dev"
    password: "dev123"
