apiVersion: v1
kind: Service
metadata:
  namespace: success-221
  name: api-success-2211
  labels:
    part-of: k8s-success
    component: backend-server
    name: api-success
    instance: api-success-2211
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-success
    component: backend-server
    name: api-success
    instance: api-success-2211
  ports:
    - port: 80
      targetPort: http
      nodePort: 32211
  type: NodePort
